### ISSUE TITLE
Support for dockercfg ImagePullSecret format

### ISSUE THREAD

**Issue by nealf** [Portshift/kubei#28]
Thanks for this project! 

It seems there are multiple ways to store ImagePullSecrets, one using the `dockerconfigjson` format and one using `dockercfg`. It looks like kubei currently [only supports the dockerconfigjson format](https://github.com/Portshift/kubei/blob/fe6bf880154eee33a9f36ac6db46bead7413d264/pkg/scanner/job-manager.go#L255), as I have jobs that fail to start with a message from the kubelet `Error: couldn't find key .dockerconfigjson in Secret default/registrycredentials` as it tries to mount the secret into the job's pod. 

I haven't been able to tell whether simply doing an if/else for mounting the correct secret value into the pod would solve this issue, or if the format of the docker secret is critical to how kubei authenticates to the image registry.

**Comment by FrimIdan** [comment]
Hi @nealf Thanks for opening this issue.
`dockercfg` is the old [format](https://github.com/moby/moby/blob/131e2bf12b2e1b3ee31b628a501f96bbb901f479/cliconfig/config.go#L18), Kubei currently supports only `dockerconfigjson` format.

This is something that can be supported (with some code changes obviously) but since it's an old format we could recommend you to update your imagePullSecrets to the new format.

**Comment by FrimIdan** [comment]
@nealf I'm closing this issue, you can reopen if more info is needed.
